version: '3'

services:
  client:
    build: 
      context: ./client
      args:
        - REACT_APP_HOST=${HOST}
    depends_on:
      - server
    restart: on-failure
    ports:
      - "80:3000"

  server:
    build: ./server
    depends_on:
      - database
    restart: on-failure
    environment:
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - "8000:8000"

  database:
    image: mongo:latest
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ./database/data:/data/db
    ports:
      - "27017"